### ISSUE TITLE
New Translation

### ISSUE THREAD

**Issue by TomHAnderson** [API-Skeletons/doctrine-in-apigility-docs_pt#1]
Thanks @sergiohermes for taking up this translation!  

The Doctrine in Apigility documentation covers many repositories.  It is at your discretion which of these to translate and when.  

This repo documentation is hosted at http://docs.apiskeletons.com/pt/latest/
Builds usually take a couple minutes after a commit has been merged to master.  

Modify index.rst to limit the documentation sections to just those you have translated.

Hit me up with any questions and thank you.

**Comment by TomHAnderson** [comment]
You have access over this repository so feel free to merge your work as you see fit.

**Comment by WanderCreate** [comment]
Hi, would you be interested in having an Italian translation done too? I am offering myself as a volunteer :)
Let me know, would be happy to contribute to the project this way.

**Comment by sergiohermes** [comment]
@BeaData  This really makes it all very interesting and makes the efforts really have value. Thank you for supporting.
For Italian translation use roadmap this repositiory [it-translate](https://github.com/API-Skeletons/doctrine-in-apigility-docs_it)

**Comment by sergiohermes** [comment]
:( I got in the way of everything here. I got edit on top, my computer is not the most efficient. excuse me.

**Comment by TomHAnderson** [comment]
@sergiohermes no problem.  You can close this issue if you'd like.  You have that authority.
